name: CI

on: workflow_dispatch

jobs:
  linux-build:
    runs-on: ubuntu-latest

    env:
      TLRENDER_NET: OFF
      TLRENDER_OCIO: ON
      TLRENDER_JPEG: ON
      TLRENDER_TIFF: ON
      TLRENDER_STB: ON
      TLRENDER_EXR: ON
      TLRENDER_FFMPEG: ON
      TLRENDER_FFMPEG_MINIMAL: ON
      TLRENDER_USD: OFF
      TLRENDER_BMD: OFF
      TLRENDER_BMD_SDK:
      FTK_API: GL_4_1

    steps:
    - uses: actions/checkout@v4
      with:
        path: DJV
        submodules: recursive
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Setup environment
      run: |
        echo "$PWD/install-Debug/bin" >> $GITHUB_PATH
        echo "LD_LIBRARY_PATH=$PWD/install-Debug/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
        echo "PYTHONPATH=$PWD/install-Debug/lib:$PYTHONPATH" >> $GITHUB_ENV
        cmake --version
        python --version
        sh DJV/etc/Linux/linux-setup-gha.sh

    - name: Build DJV
      run: sh DJV/etc/Linux/linux-build-gha.sh Debug

  linux-gles2-build:
    runs-on: ubuntu-latest

    env:
      TLRENDER_NET: OFF
      TLRENDER_OCIO: OFF
      TLRENDER_JPEG: ON
      TLRENDER_TIFF: ON
      TLRENDER_STB: ON
      TLRENDER_EXR: ON
      TLRENDER_FFMPEG: ON
      TLRENDER_FFMPEG_MINIMAL: OFF
      TLRENDER_USD: OFF
      TLRENDER_BMD: OFF
      TLRENDER_BMD_SDK:
      FTK_API: GLES_2

    steps:
    - uses: actions/checkout@v4
      with:
        path: DJV
        submodules: recursive
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Setup environment
      run: |
        echo "$PWD/install-Debug/bin" >> $GITHUB_PATH
        echo "LD_LIBRARY_PATH=$PWD/install-Debug/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
        echo "PYTHONPATH=$PWD/install-Debug/lib:$PYTHONPATH" >> $GITHUB_ENV
        cmake --version
        python --version
        python --version
        sh DJV/etc/Linux/linux-setup-gha.sh

    - name: Build DJV
      run: sh DJV/etc/Linux/linux-build-gha.sh Debug

  linux-package:
    runs-on: ubuntu-22.04

    env:
      TLRENDER_NET: OFF
      TLRENDER_OCIO: ON
      TLRENDER_JPEG: ON
      TLRENDER_TIFF: ON
      TLRENDER_STB: ON
      TLRENDER_EXR: ON
      TLRENDER_FFMPEG: ON
      TLRENDER_FFMPEG_MINIMAL: OFF
      TLRENDER_USD: ON
      TLRENDER_BMD: OFF
      TLRENDER_BMD_SDK:
      FTK_API: GL_4_1

    steps:
    - uses: actions/checkout@v4
      with:
        path: DJV
        submodules: recursive
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Setup environment
      run: |
        echo "$PWD/install-Release/bin" >> $GITHUB_PATH
        echo "LD_LIBRARY_PATH=$PWD/install-Release/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
        echo "PYTHONPATH=$PWD/install-Release/lib:$PYTHONPATH" >> $GITHUB_ENV
        cmake --version
        python --version
        python --version
        sh DJV/etc/Linux/linux-setup-gha.sh

    - name: Build DJV
      run: sh DJV/etc/Linux/linux-build-gha.sh Release

    - name: Package
      run: cmake --build build-Release -j 4 --target package

    - uses: actions/upload-artifact@v4
      with:
        name: DJV-Linux-Packages
        path: build-Releae/DJV-*.tar.gz

  macos-13-build:
    runs-on: macos-13

    env:
      TLRENDER_NET: OFF
      TLRENDER_OCIO: ON
      TLRENDER_JPEG: ON
      TLRENDER_TIFF: ON
      TLRENDER_STB: ON
      TLRENDER_EXR: ON
      TLRENDER_FFMPEG: ON
      TLRENDER_FFMPEG_MINIMAL: OFF
      TLRENDER_USD: OFF
      TLRENDER_BMD: OFF
      TLRENDER_BMD_SDK:
      FTK_API: GL_4_1
      CMAKE_OSX_DEPLOYMENT_TARGET: 10.15
      CMAKE_OSX_ARCHITECTURES: x86_64

    steps:
    - uses: actions/checkout@v4
      with:
        path: DJV
        submodules: recursive
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # \bug DYLD_LIBRARY_PATH is not being set here?
    - name: Setup environment
      run: |
        echo "$PWD/install-Debug/bin" >> $GITHUB_PATH
        echo "DYLD_LIBRARY_PATH=$PWD/install-Debug/lib:$DYLD_LIBRARY_PATH" >> $GITHUB_ENV
        echo "PYTHONPATH=$PWD/install-Debug/lib:$PYTHONPATH" >> $GITHUB_ENV
        cmake --version
        python --version

    - name: Build DJV
      run: |
        export DYLD_LIBRARY_PATH=$PWD/install-Debug/lib:$DYLD_LIBRARY_PATH
        sh DJV/etc/macOS/macos-build-gha.sh Debug

  macos-build:
    runs-on: macos-latest

    env:
      TLRENDER_NET: OFF
      TLRENDER_OCIO: ON
      TLRENDER_JPEG: ON
      TLRENDER_TIFF: ON
      TLRENDER_STB: ON
      TLRENDER_EXR: ON
      TLRENDER_FFMPEG: ON
      TLRENDER_FFMPEG_MINIMAL: OFF
      TLRENDER_USD: OFF
      TLRENDER_BMD: OFF
      TLRENDER_BMD_SDK:
      FTK_API: GL_4_1
      CMAKE_OSX_DEPLOYMENT_TARGET: 14
      CMAKE_OSX_ARCHITECTURES: arm64

    steps:
    - uses: actions/checkout@v4
      with:
        path: DJV
        submodules: recursive
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # \bug DYLD_LIBRARY_PATH is not being set here?
    - name: Setup environment
      run: |
        echo "$PWD/install-Debug/bin" >> $GITHUB_PATH
        echo "DYLD_LIBRARY_PATH=$PWD/install-Debug/lib:$DYLD_LIBRARY_PATH" >> $GITHUB_ENV
        echo "PYTHONPATH=$PWD/install-Debug/lib:$PYTHONPATH" >> $GITHUB_ENV
        cmake --version
        python --version

    - name: Build DJV
      run: |
        export DYLD_LIBRARY_PATH=$PWD/install-Debug/lib:$DYLD_LIBRARY_PATH
        sh DJV/etc/macOS/macos-build-gha.sh Debug

  macos-package:
    runs-on: macos-latest

    env:
      TLRENDER_NET: OFF
      TLRENDER_OCIO: ON
      TLRENDER_JPEG: ON
      TLRENDER_TIFF: ON
      TLRENDER_STB: ON
      TLRENDER_EXR: ON
      TLRENDER_FFMPEG: ON
      TLRENDER_FFMPEG_MINIMAL: OFF
      TLRENDER_USD: ON
      TLRENDER_BMD: OFF
      TLRENDER_BMD_SDK:
      FTK_API: GL_4_1
      CMAKE_OSX_DEPLOYMENT_TARGET: 10.15
      CMAKE_OSX_ARCHITECTURES: arm64

    steps:
    - uses: actions/checkout@v4
      with:
        path: DJV
        submodules: recursive
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # \bug DYLD_LIBRARY_PATH is not being set here?
    - name: Setup environment
      run: |
        echo "$PWD/install-Release/bin" >> $GITHUB_PATH
        echo "DYLD_LIBRARY_PATH=$PWD/install-Release/lib:$DYLD_LIBRARY_PATH" >> $GITHUB_ENV
        echo "PYTHONPATH=$PWD/install-Release/lib:$PYTHONPATH" >> $GITHUB_ENV
        cmake --version
        python --version

    - name: Build DJV
      run: |
        export DYLD_LIBRARY_PATH=$PWD/install-Release/lib:$DYLD_LIBRARY_PATH
        sh DJV/etc/macOS/macos-build-gha.sh Release

    # \bug Sometimes the CI runs out of disk space when building the macOS
    # package, so free some up by removing the super build directory.
    - name: Package
      run: |
        rm -rf sbuild-Release
        cmake --build build-Release -j 4 --target package

    - uses: actions/upload-artifact@v4
      with:
        name: DJV-macOS-Packages
        path: build-Release/DJV-*.dmg

  windows-build:
    runs-on: windows-latest

    env:
      TLRENDER_NET: OFF
      TLRENDER_OCIO: ON
      TLRENDER_JPEG: ON
      TLRENDER_TIFF: ON
      TLRENDER_STB: ON
      TLRENDER_EXR: ON
      TLRENDER_FFMPEG: ON
      TLRENDER_FFMPEG_MINIMAL: OFF
      TLRENDER_USD: OFF
      TLRENDER_BMD: OFF
      TLRENDER_BMD_SDK:
      FTK_API: GL_4_1

    steps:
    - uses: actions/checkout@v4
      with:
        path: DJV
        submodules: recursive
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - uses: ilammy/setup-nasm@v1

    # \bug Any spaces before the ">>" will be considered part of the path.
    - name: Setup environment
      shell: cmd
      run: |
        echo %CD%\install-Debug\bin>> %GITHUB_PATH%
        echo %CD%\install-Debug\lib>> %GITHUB_PATH%
        echo CTEST_OUTPUT_ON_FAILURE=1 >> %GITHUB_ENV%
        cmake --version
        python --version
        
    - name: Build DJV
      shell: cmd
      run: DJV\etc\Windows\windows-build-gha.bat Debug

  windows-package:
    runs-on: windows-latest

    env:
      TLRENDER_NET: OFF
      TLRENDER_OCIO: ON
      TLRENDER_JPEG: ON
      TLRENDER_TIFF: ON
      TLRENDER_STB: ON
      TLRENDER_EXR: ON
      TLRENDER_FFMPEG: ON
      TLRENDER_FFMPEG_MINIMAL: OFF
      TLRENDER_USD: ON
      TLRENDER_BMD: OFF
      TLRENDER_BMD_SDK:
      FTK_API: GL_4_1

    steps:
    - uses: actions/checkout@v4
      with:
        path: DJV
        submodules: recursive
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - uses: ilammy/setup-nasm@v1

    # \bug Any spaces before the ">>" will be considered part of the path.
    - name: Setup environment
      shell: cmd
      run: |
        echo %CD%\install-Release\bin>> %GITHUB_PATH%
        echo %CD%\install-Release\lib>> %GITHUB_PATH%
        echo CTEST_OUTPUT_ON_FAILURE=1 >> %GITHUB_ENV%
        cmake --version
        python --version

    - name: Build DJV
      shell: cmd
      run: DJV\etc\Windows\windows-build-gha.bat Release

    - name: Package
      shell: cmd
      run: cmake --build build-Release -j 4 --config Release --target package

    - uses: actions/upload-artifact@v4
      with:
        name: DJV-Windows-Packages
        path: |
          build-Release\DJV-*.exe
          build-Release\DJV-*.zip
